dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  flutter_svg: ^2.0.7
  http: ^0.13.5

dev_dependencies:
  hive_generator: ^1.1.3
  build_runner: ^2.3.3
